### ISSUE TITLE
💀 browserType.connect: Unauthorized, either Username or AccessKey is invalid.

### ISSUE THREAD

**Issue by mystcuro** [LambdaTest/playwright-sample#31]
Steps:
1. clone 
2. npm install
3. windows system environmental variable set for username and access key
Got error during running the command=> node playwright-single.js
error: browserType.connect: Unauthorized, either Username or AccessKey is invalid. 
 
tried installing dotenv package and storing username and keys in .env file
still same error. 💀

**Comment by ankur-lt** [comment]
@mystcuro , you can try first expotying the environment variables in the terminal and then use the same terminal session to run script.
For usinggg `dotenv` NPM library, make sure you are loading the dotenv library before the test starts using
```js
require('dotenv').config()
```
