### ISSUE TITLE
[BUG] This example doesn't work with Playwright 1.24.3+ versions

### ISSUE THREAD

**Issue by dskochubey** [LambdaTest/playwright-sample#39]
When running the example, I see an error: `browserType.connect: Playwright version 1.27.0 not supported. Supported versions are 1.19.0 to 1.24.2`. How to fix that error and run tests with Playwright 1.27.0 and LambdaTest?

**Comment by ankur-lt** [comment]
@dskochubey , can you try again? We have added support for the latest versions too now.
