### ISSUE TITLE
`storageState` `(test.use({storageState: 'filename.json'})` seems not working while using `lambdatest-setup.js`

### ISSUE THREAD

**Issue by iamarbabhussain** [LambdaTest/playwright-sample#40]
Using lambdatest runner with playwright, when we use `lambdatest-setup.js` file and import `test` from this file, `storageState` which is used by `test.use()` to use authenticated json file does not seem to work. Is it a knwon bug or am I missing something?

**Comment by christophe-gamned** [comment]
Hello,
I have the same problem. Here a simple snippet to explain issue.

`
[...]
const { expect } = require('@playwright/test');
const { test } = require('../lambdatest-setup')

test.use({ storageState: 'storageState.json' });

test('logout', async ({ page }) => {
   await expect(page.getByRole('link', { name: 'Login' }).count()).toEqual(0)
   await expect(page.getByRole('link', { name: 'Hi ! You are logged' }).first()).toBeVisible();
   await page.getByRole('link', { name: 'Hi ! You are logged' }).first().click();
   await page.getByRole('link', { name: 'Logout' }).click();
   await expect(page.getByRole('link', { name: 'Login' })).toBeVisible();
});

[...]
`

**Comment by ankur-lt** [comment]
Hello @christophe-gamned ,
   You are using the functions exposed by `@playwright/test` runner, which is running on the local machine while the test is running on a remote machine. Can you try using the below code snippet to make this work:
   
```js
const { test } = require('../lambdatest-setup')
const { expect } = require('@playwright/test')
const state = require('../state1.json')

test.use({ storageState: state });
test.only('Search LambdaTest on Bing', async ({ page }) => {
...
})
```

**Comment by vipulkv** [comment]
@ankur-lt 👍

**Comment by christophe-gamned** [comment]
@ankur-lt accord my last tests executions, both snippets (your and mine) work.
